### ISSUE TITLE
Comments on Single session based storages for multiple TelegramClients

### ISSUE THREAD

**Issue by uwinx** [uwinx/garnet#7]
Currently you can try to use [asyncpg|async session](github.com/uwinx/telethon-async-session) as a backend telethon. It must not affect any garnet feature, except some typing parts related.
In upcoming update(big one :smile:), I'll make sure different backend can be used.

**Comment by x0x8x** [comment]
> 
> 
> Currently you can try to use [asyncpg|async session](github.com/uwinx/telethon-async-session) as a backend telethon. It must not affect any garnet feature, except some typing parts related.
> In upcoming update(big one smile), I'll make sure different backend can be used.

wrong link has been added to [](https://github.com/uwinx/telethon-async-session)

**Comment by uwinx** [comment]
it's no longer an issue since [telethon_asyncpg](https://github.com/ukinti/telethon_asyncpg) is just a garnet-like patch for existing telethon.

Haven't tested integration tho. Feel free to reopen.
